- source/includes/_claimsconvert.md
- source/includes/_claimstatus.md
- source/includes/_files.md
- source/includes/_icdconvert.md
- source/index.md
documentation for the new /icd/convert and /claims/convert APIs that were released today at Health 2.0
> PLATFORM-2415: API documentation for /icd/convert and /claims/convert

- source/benefits_enrollment.md
the documentation’s being updated to reflect additional fields that are supported for the member and benefits objects
> PLATFORM-2353 

- source/includes/_scheduling.md
* Added /scheduling/patient
* Updated /scheduling/appointmenttypes to include the correct response information
* Added /schedule/slots
> Platform 2495: Scheduling API Updates

- .gitignore
- source/includes/_eligibility.md
Added some return fields for eligibility API response and corresponding documentation.
This is coinciding with PLATFORM-2855
> Platform 2887 adding returns for eligibility api for authorization_required and service_type_codes

- source/includes/_providers.md
update provider API documentation with all nested fields.  add Option or Optional/Deprecated where applicable.
> PLATFORM-2950 update provider API documentation (REVIEW)

- source/includes/_identity.md
- updated GET (query) search parameters
- updated GET endpoint table to indicate that results are returned within an array
- Tweaks to get /identity verbiage matched up with /providers
> PLATFORM-2686: IDM updates

- source/includes/_identity.md
Initial Pass at adding wording around the three different components of the /identity product. 
Also,  initial pass of the available documentation for /identity/match
> Platform 2852

- source/includes/_activities.md
- source/includes/_authorizations.md
- source/includes/_cashprices.md
- source/includes/_claims.md
- source/includes/_claimstatus.md
- source/includes/_common.md
- source/includes/_eligibility.md
- source/includes/_enrollment.md
- source/includes/_files.md
- source/includes/_icdconvert.md
- source/includes/_identity.md
- source/includes/_insuranceprices.md
- source/includes/_mpc.md
- source/includes/_plans.md
- source/includes/_providers.md
- source/includes/_referrals.md
- source/includes/_scheduling.md
- source/includes/_tradingpartners.md
> PLATFORM-2981

- source/includes/_providers.md
add address_lines to supported query request arguments
> PLATFORM-2959 add address_lines to supported query request arguments (REVIEW)

- source/includes/_eligibility.md
Added group_number to parameters and example.  Added example request
with service_types.  Updated unable_to_respond_now response.
> PLATFORM-3010: Add group_number to eligibility request

- source/includes/_providers.md
- source/provider_specialties.md
add documentation for provider specialties.   this includes a new page with the full specialties list and also ability to specify partial specialty-prefix in the search request.
> PLATFORM-3373 add documentation for provider specialties (REVIEW)

- source/includes/_common.md
add the new meta section message field
> PLATFORM-3370 add the new meta section message field (REVIEW)

- source/includes/_claims.md
Changes to dates and diagnoses codes in existing claims sample requests.  Edits starting line 2719 to claims introduction verbiage.
> PLATFORM-3605_Claims Documentation Updates

- source/includes/_eligibility.md
this will be deployed in conjunction with associated pull request merge in OHP (TBD)
> Platform-3370 update documentation for trading partner outages

- deploy.sh
- deployer.py
this new deploy.sh creates a local branch off dev to freeze contributions at that point, then deploys that to staging. Then you are prompted to verify staging’s correctness. If correct, merges that local branch into master and goes to deploy to prod from there. Then cleans up.
> ENTERPRISE-281: add deploy script to incorporate git process

- source/includes/_eligibility.md
update link to PokitDok status page with outage details
> PLATFORM-3370 update link to PokitDok status page with outage details (REVIEW)

- README.md
- source/includes/_cashprices.md
Completion of [ENTERPRISE-317](https://pokitdok.atlassian.net/browse/ENTERPRISE-317) ticket which entailed the updating of the cash prices API endpoint client libraries code examples.
> ENTERPRISE-317 : Cash Prices Endpoint Client Libraries Code Updates

- source/includes/_eligibility.md
Removal of NPI verbiage and add reference to supported search options.
> PLATFORM-3318_Eligibility content updates

- source/includes/_files.md
Completion of [ENTERPRISE-322](https://pokitdok.atlassian.net/browse/ENTERPRISE-322) ticket which entailed the updating of the files API endpoint general documentation.
> ENTERPRISE-322 : Files Endpoint General Documentation Updates

- source/includes/_insuranceprices.md
Completion of [ENTERPRISE-332](https://pokitdok.atlassian.net/browse/ENTERPRISE-332) ticket which entailed the updating of the insurance prices API client library code examples.
> ENTERPRISE-332 : Insurance Prices Endpoint Client Library Code Example Updates

- source/includes/_mpc.md
Completion of [ENTERPRISE-324](https://pokitdok.atlassian.net/browse/ENTERPRISE-324) ticket which entailed the updating of the MPC API client library code examples.
> ENTERPRISE-324 : MPC Endpoint Client Library Code Example Updates

- source/includes/_providers.md
Completion of [ENTERPRISE-348](https://pokitdok.atlassian.net/browse/ENTERPRISE-348) ticket which entailed the updating of the providers API endpoint general documentation.
> ENTERPRISE-348 : Providers Endpoint General Documentation Updates

- source/includes/_authorizations.md
- source/includes/_referrals.md
Completion of [ENTERPRISE-350](https://pokitdok.atlassian.net/browse/ENTERPRISE-350) ticket which entailed the updating of the referrals API endpoint general documentation.
> ENTERPRISE-350 : Refferals Endpoint General Documentation Updates

- source/includes/_providers.md
Completion of [ENTERPRISE-335](https://pokitdok.atlassian.net/browse/ENTERPRISE-335) ticket which entailed the updating of the providers API client library code examples.
> ENTERPRISE-335 : Providers Endpoint Client Library Code Example Updates

- source/includes/_scheduling.md
Completion of [ENTERPRISE-338](https://pokitdok.atlassian.net/browse/ENTERPRISE-338) ticket which entailed the updating of the scheduling API client library code examples.
> ENTERPRISE-338 : Scheduling Endpoint Client Library Code Example Updates

- source/includes/_tradingpartners.md
Completion of [ENTERPRISE-338](https://pokitdok.atlassian.net/browse/ENTERPRISE-340) ticket which entailed the updating of the trading partners API client library code examples.
> ENTERPRISE-340 : Trading Partners Client Library Code Example Updates

- source/includes/_identity.md
Completion of [PLATFORM-3733](https://pokitdok.atlassian.net/browse/PLATFORM-3733) ticket which entailed the updating of the IdM API endpoint general documentation.
> PLATFORM-3733 : IdM Endpoint General Documentation Update

- source/includes/_scheduling.md
Completion of [ENTERPRISE-337](https://pokitdok.atlassian.net/browse/ENTERPRISE-337) ticket which entailed the updating of the scheduling API endpoint general documentation.
> ENTERPRISE-337 : Scheduling Endpoint General Documentation Update

- source/includes/_enrollment.md
Completion of [ENTERPRISE-389](https://pokitdok.atlassian.net/browse/ENTERPRISE-389) ticket which entailed adding a small amount to the enrollment docs regarding individual enrollment.
> ENTERPRISE-389: Minor Update to the Enrollment Documentation

- source/includes/_eligibility.md
change to correct invalid dob messaging as well as general clean up for consistency.
> PLATFORM-3817_Eligibility Reject Reason Updates

- source/includes/_activities.md
Added clarification on when activities are no longer eligible for cancellation
> PLATFORM-3903_Activities cancel clarification

- source/includes/_activities.md
- source/includes/_authorizations.md
- source/includes/_claims.md
- source/includes/_claimstatus.md
- source/includes/_common.md
- source/includes/_eligibility.md
- source/includes/_enrollment.md
- source/includes/_enrollmentsnapshot.md
- source/includes/_icdconvert.md
- source/includes/_identity.md
- source/includes/_referrals.md
- source/includes/_scheduling.md
- source/includes/_tradingpartners.md
Completion of ticket [ENTERPRISE-422](https://pokitdok.atlassian.net/browse/ENTERPRISE-422) which entailed syncing the docs with the newly implemented ruby endpoints.
Also added docs for the python general request method.
> ENTERPRISE-422: Update the Documentation for Unsupported Methods

- source/includes/_eligibility.md
Addition of details surrounding where to find search option combinations
> PLATFORM-3904_Eligibility_supported search options

- source/includes/_eligibility.md
Completion of [ENTERPRISE-426](https://pokitdok.atlassian.net/browse/ENTERPRISE-426) which entailed the fixing of the representation of the `service_types` property on the eligibility endpoint.
> ENTERPRISE-426 : fix documentation example for eligibility service_types to show a list

- source/includes/_providers.md
add facilities and entity_type fields into response documentation and examples
> PLATFORM-4395 add facilities and entity_type fields into response docs (REVIEW)

- source/includes/_eligibility.md
Addition of military personnel information under subscriber object as well as new object creation.
> PLATFORM-4414_Military Personnel Information

- source/includes/_eligibility.md
removal of duplicated invalid_subscriber_insured_name
> PLATFORM-4490_Remove duplicate reject reason code

- source/includes/_pharmacy_formulary.md
- source/includes/_pharmacy_network.md
- source/includes/_pharmacy_plans.md
Presence column in pharmacy APIs: networks, plans, and formularies
> ENTERPRISE-623 Presence column in pharmacy APIs

- source/includes/_pharmacy_plans.md
added the zipcode response field to the docs
and showed its use in an example
> PLATFORM-4581 zipcode in pharma plans API request

- source/includes/_dropin.md
fix broken #options page link in dropin UI step 4 remove leading slash
> PLATFORM-4775 fix broken #options page link in dropin UI step 4 remove leading slash

- source/includes/_raw_x12_support.md
- source/index.md
These adjustments document the platform's support for handling Raw X12 transactions with the X12-based APIs.
> PLATFORM-4694: new Raw X12 Support documentation section

- source/includes/_raw_x12_support.md
These adjustments incorporate a refinement to the `Raw X12 Support` section to link to our trading partners page.
https://github.com/pokitdok/apidocs-v4/pull/158#discussion_r88706440
> PLATFORM-4694: include link to trading partners page in Raw X12 Support section

- source/includes/_clientlibraries.md
https://pokitdok.atlassian.net/browse/PLATFORM-5014
> PLATFORM-5014: Add Apex link

- source/includes/_authorizations.md
add new PER fields (fax, email, url) for provider
this should be merged/deployed when pokitedi v1.0.55 deploys
> PLATFORM-4963 add new PER fields (fax, email, url) for provider

- source/includes/_oop_insurance.md
https://pokitdok.atlassian.net/browse/PLATFORM-5043
https://github.com/PokitDokInc/ohp/pull/3173
> PLATFORM-5043: Update OOP Docs to include price load DELETE

- source/includes/_claimstatus.md
Update claim status docs to display status category code
> PLATFORM-5090 Update Claims status example to include status_cetegory_code

- source/includes/_activities.md
added to parameters and example
> PLATFORM-5079_Add callback_error to Activities

- source/includes/_claims.md
Several issue reported by client.
> PLATFORM-5107: Update COB object.

- source/includes/_dropin.md
- Added new options to dropin documentation for changing input labels
> PLATFORM-4908: Update to dropin documentation

- source/includes/_clientlibraries.md
Split the table to show which languages have convenience functions.
> ENTERPRISE-395

- source/includes/_claims.md
> PLATFORM-5161_Add Claims Response Examples

- deployer.py
change tabs to spaces and fix other broken indentation and exception references
> change tabs to spaces and fix other broken indentation and exception references

- source/provider_specialties.md
remove dead link to old pd marketplace
> remove dead link to old pd marketplace

- source/includes/_claims.md
remove other subscriber references and object, addition of payer amount paid and amount owed to coordination of benefits object, fixed procedure modifiers to procedure modifier codes
> EV-13_Coordination of Benefits changes

- source/includes/_claims.md
addition of new parameters, a few changed
> SUCCESS-67_Coordination of Benefits docs revamp

- source/includes/_plans.md
update plans documentation for 2017 data release
> EV-88 update plans documentation for 2017 data release

- source/includes/_providers.md
adding note about the length of the zipcode
> SUCCESS-144

- source/includes/_authentication.md
This PR updates our cURL authentication example to utilize a script which will complete successfully on Darwin (OS X) and Linux variants such as Ubuntu. The general issue here is that the base64 and sed programs differ between these two platforms. This PR addresses that issue by cleaning up base64 output, if needed, with the tr program.
> SUCCESS-117: Updating cURL authentication for multiple Platforms

- source/includes/_claims.md
This PR updates our Claim documentation to include the new COB related adjustment and adjudication entries, along with code snippets for shell, python, ruby, c#, and swift. I'll update Java within the next day or so.
> SUCCESS-244: Claim COB Updates 

- source/includes/_claims.md
Need to add changes made in  SUCCESS-201  to docs. Will want to include new fields, descriptions, and example.
Options
> EV-105 Update Docs to reflect COB changes included in SUCCESS-201

- source/includes/_cashprices.md
- source/includes/_insuranceprices.md
Updating our docs to reflect the csharp client release
https://github.com/pokitdok/pokitdok-csharp/blob/master/PlatformClient.cs#L273
https://github.com/pokitdok/pokitdok-csharp/blob/master/PlatformClient.cs#L526
> EV-40: updating the csharp examples in the prices docs

- source/includes/_scheduling.md
the github client change: https://github.com/pokitdok/pokitdok-csharp/blob/master/PlatformClient.cs#L855
> EV-49: updating create_slot example to scheduleSlots

- source/includes/_claims.md
Updated 835 example for addition of support for GS04 and LQ segments.
> SUCCESS-470_Support for created date and remarks on 835

- source/includes/_pharmacy_network.md
remove plan_name from pharmacy networks request, add plan_number to response
> SUCCESS-475 remove plan_name from pharmacy networks request, add plan_number to response

- source/includes/_claims.md
- source/includes/_payments.md
- source/index.md
Some initial documentation for Payments API endpoints that will allow API clients to search and retrieve payment information that has been associated with their application.
> X12-565: Payments APIs

- source/includes/_authorizations.md
DKG added: 
```
Removed wording around "payload" and "parameters"
```
> Staging review changes

- source/includes/_payments.md
Update payments documentation to include more example snippets
> X12-565: include client library language snippets for payments

- source/includes/_payments.md
The Payments API will soon support date range searches for effective date and received date.
This update adds these new request parameters to the supported search parameters for `GET /payments/` requests.
> SUCCESS-663: introduce new effective date and received date range search options for the Payments API

- source/includes/_claims.md
addition of new values to place of service code set for telehealth and off_campus_outpatient_hospital
> SUCCESS-689_Place of Service code set modifications

- source/includes/_activities.md
Updating the /activities response to include payment_id.
> SUCCESS-1041 Add payment_id to activity response.

- source/includes/_raw_x12_support.md
We have a new content type for full X12-JSON now available, updating documentation to reflect that.
> X12-799 Full X12-JSON Documentation.

- source/includes/_eligibility.md
Add ‘coverage.benefit_begin’ and 'coverage.plan_benefit_description.benefit_begin'. Add an example medicare_national eligibility request including HCPCS code.
> SUCCESS-995

- source/includes/_dropin.md
- Added pharmacy-coverage dropin documentation with examples
- Fixed some minor formatting issues on other dropin documentation types
> PHARMA-145: Added new pharmacy-coverage type to dropin documentation

- source/includes/_claimsdrafts.md
Add in verbiage about what the draft API is.
> ENTRY-2818 Add description to drafts api in our documentation

- source/index.md
add links to sidebar per MB-853 request
> MB-853: add links on sidebar footer to pokitdok.com and other common footer items

- source/includes/_oop_insurance.md
Adding documentation to new GET endpoints added to the OOP API.
> SUCCESS-1922 Add GET /oop/insurance-load-price documentation.

- source/includes/_appregistrations.md
- source/includes/_consumerhco.md
- source/index.md
Add Consumer HCO API documentation.
> SUCCESS-2115 Add Consumer HCO API documentation.

- source/includes/_providers.md
add lat_lon request argument
* also made a few other descriptions consistent with verbiage
> POC-140 add lat_lon request argument

- source/includes/_activities.md
https://pokitdok.atlassian.net/browse/ENTRY-4436
> Update doc to reflect new tracking descriptions

- Gemfile.lock
- source/includes/_authentication.md
- source/includes/_clientlibraries.md
- source/index.md
Update and expand the authentication documentation to be more descriptive about oauth token handling.
> SUCCESS-2718: Update authentication documentation to be more descriptive

- source/includes/_pharmacy_plans.md
add zipcode request parameter to pharmacy plans API
> add zipcode request parameter to pharmacy plans API

- source/includes/_pharmacy_network.md
add mail and retail boolean args to pharmacy network API
> add mail and retail boolean args to pharmacy network API
