pokitdok/apidocs-v4

source/includes/_activities.md
source/includes/_apicallbacks.md
source/includes/_authentication.md
source/includes/_authorizations.md
source/includes/_cashprices.md
source/includes/_claims.md
source/includes/_claimstatus.md
source/includes/_eligibility.md
source/includes/_enrollment.md
source/includes/_insuranceprices.md
source/includes/_mpc.md
source/includes/_plans.md
source/includes/_providers.md
source/includes/_referrals.md
source/includes/_tradingpartners.md

When API clients wish to test mock claim payment callbacks with their test claims sent to the `MOCKPAYER` trading partner, they can include:
```
"application_data": {
"mock_claim_payment": True
}
```
in their test claims requests and they'll receive a second callback (after the initial claim acknowledgement callback) that will include a mock claim payment result.
They'll receive a callback within a few minutes indicating the claim was accepted for processing with a claim acknowledgement. Around a minute after that first callback, they'll receive a second callback indicating the claim was paid and the activity result will contain claim payment information.
This set up changes adds an example for how a new API client might test their application with this functionality.   Also included some …

PLATFORM-2269: API documentation for mock claim payment callbacks

---

source/includes/_enrollmentsnapshot.md
source/includes/_files.md
source/index.md

API documentation for the new enrollment snapshot functionality
API client applications may now easily interact with trading partners that require full 834 files each time changes are transmitted.   Applications simply establish the current state of membership enrollment for a group/trading partner and then can continue making enrollment API requests for additions, changes, terminations, etc.   Full file 834 construction and delivery is handled in the background based on an application's scheduled enrollment requests combined with the current enrollment snapshot data.

PLATFORM-2526: Document new enrollment snapshot functionality

---

source/includes/_eligibility.md

Brought about by recent confusion from clients about the Summary information presented in the Eligibility response, starting at row 189 we've inserted a snip about our Summary section and what it can and should be used for.  Also added Summary to json successful eligibility response starting at row 296.

Add details about Summary in Eligibility Response Documentation

---

source/includes/_claims.md

Added new sample claim (including rendering provider details) at line 931 along with parameter updates to include (institutional claim specific) starting at 1047 and rendering provider starting at 1056.

Addition of Rendering Provider to Claims Documentation

---

source/includes/_identity.md
source/includes/_scheduling.md
source/index.md

IDM Documentation:
- initial add to support /identity
- verbiage is lifted from Platform API workflows site
- supported query parameters are indexed health graph fields
- I still need to double-check markdown formatting locally. I'll post on the PR once that is confirmed
Scheduling Documentation:
- fixed some formatting issues where code examples were displayed within the "prose"

PLATFORM-2822: IDM and Scheduling documentation updates. 

---

source/includes/_eligibility.md

Eligibility API documentation updates to highlight `pharmacy` section and the information that may be returned by a trading partner and included in the `pharmacy` section.   
Here's an example `pharmacy` section based on a sample medicare member with a Medicare Part D Prescription Drug Plan:
```
"pharmacy": {
"benefits_manager": {
"name": "UNITEDHEALTHCARE INSURANCE COMPANY",
"phone": "8778423210",
"url": "www.AARPMedicareRx.com"
},
"is_eligible": true,
"plan_number": "S5820 003"
}
```

PLATFORM-2849: eligibility API pharmacy fields

---

source/includes/_identity.md

Updates to /identity documentation:
- added "address" as a search parameter

PLATFORM-3034: Adding address to /identity query parameter list

---

source/includes/_activities.md
source/includes/_authorizations.md
source/includes/_cashprices.md
source/includes/_claims.md
source/includes/_claimstatus.md
source/includes/_common.md
source/includes/_eligibility.md
source/includes/_enrollment.md
source/includes/_files.md
source/includes/_icdconvert.md
source/includes/_identity.md
source/includes/_insuranceprices.md
source/includes/_mpc.md
source/includes/_plans.md
source/includes/_providers.md
source/includes/_referrals.md
source/includes/_scheduling.md
source/includes/_tradingpartners.md

API documentation updates to provide examples for using the csharp client. We didn't really have any examples before. 
I also added a section in the documentation for `Generic` request handlers. Currently only the csharp client has an example usage.

PLATFORM-2981

---

source/includes/_claims.md

Update to claims api doc, to include service_end_date in sample requests. Updated the CMS reference for service_date to more pointedly map to the 'from' and the service_end_date to map to the 'to' date, if entering a date range.

PLATFORM-3194 update Claims doc for service_end_date

---

source/includes/_cashprices.md

Added the pokitdok_procedure_urn and procedure_description fields to the
documentation for the cash price API, as well as corrected the other
field names.

PLATFORM-3256: Update cash API documentation

---

Dockerfile

Updated the Dockerfile so that it installs the right version of ruby as
well as installing the dependencies for nokogiri.

PLATFORM-3258: Fix Dockerfile

---

source/includes/_cashprices.md

Old Request ![image](https://cloud.githubusercontent.com/assets/16102952/15323655/240e2f3e-1c11-11e6-8d3e-f90069b67fb2.png) 
New Request ![image](https://cloud.githubusercontent.com/assets/16102952/15323714/56e5dcb8-1c11-11e6-9cdd-486c0f8f95c2.png)

AG_DOCFIX_1: Changed cpt_code of cash price example from 87799 to 97001

---

source/includes/_common.md

- Removed code samples for languages that don't have tabs anymore which fixed duplicate "See cURL example" text

UTEST-1942: Fixed duplicate messaging

---

source/includes/_claims.md

Completion of [ENTERPRISE-304](https://pokitdok.atlassian.net/browse/ENTERPRISE-304) ticket which entailed the updating of the claims API endpoint client code examples.

ENTERPRISE-304 : Claims Endpoint Client Code Examples Updates

---

source/includes/_clientlibraries.md

Completion of [ENTERPRISE-315](https://pokitdok.atlassian.net/browse/ENTERPRISE-315) ticket which entailed removing dead links of the Lua and Haskell client libraries.

ENTERPRISE-315 : Updates to the Client Library Documentation Section

---

source/includes/_enrollmentsnapshot.md

Completion of [ENTERPRISE-321](https://pokitdok.atlassian.net/browse/ENTERPRISE-321) ticket which entailed the updating of the enrollment snapshot API client library code examples.
Only thing I'm not too sure about it the aws s3 URL in one of the responses.

ENTERPRISE-321 : Enrollment Snapshot Endpoint Client Library Code Example Updates

---

source/includes/_files.md

Completion of [ENTERPRISE-323](https://pokitdok.atlassian.net/browse/ENTERPRISE-323) ticket which entailed the updating of the files API client library code examples.

ENTERPRISE-323 : Files Endpoint Client Library Code Example Updates

---

source/includes/_plans.md

Completion of [ENTERPRISE-347](https://pokitdok.atlassian.net/browse/ENTERPRISE-347) ticket which entailed the updating of the plans API endpoint general documentation.

ENTERPRISE-347 : Plans Endpoint General Documentation Updates

---

source/includes/_authorizations.md
source/includes/_claimstatus.md
source/includes/_eligibility.md
source/includes/_referrals.md

Completion of [ENTERPRISE-393](https://pokitdok.atlassian.net/browse/ENTERPRISE-393) ticket which entailed the adding of `client_id` to descriptions and response JSON to endpoints that returned `client_id` in their `data` sections.

ENTERPRISE-393: Adding client_id to docs

---

source/includes/_providers.md

Completion of ticket [ENTERPRISE-433](https://pokitdok.atlassian.net/browse/ENTERPRISE-433) which entailed the addition of the `name` parameter to the providers request.

ENTERPRISE-433 : add 'name' to provider API request arguments

---

source/includes/_providers.md

Completion of ticket [ENTERPRISE-425](https://pokitdok.atlassian.net/browse/ENTERPRISE-425) which entailed the adding of `entity_type(s)` to the provider request/response models.

ENTERPRISE-425 : add entity_types / entity_type to provider API request/response

---

source/includes/_providers.md

add quotes around provider API URLs in curl examples

ENTERPRISE-494 add quotes around provider API URLs in curl examples (REVIEW)

---

source/includes/_pharmacy_formulary.md

the following fields in the formulary response should be optional:
* limit_amount
* limit_days
* retail.oop_30_day
* retail.total_cost_30_day
* retail.ins_pay_30_day
* mail.oop_90_day
* mail.total_cost_90_day
* mail.ins_pay_90_day

PLATFORM-3905 - documenting option fields in formulary API response

---

source/index.md

Completion of ticket [ENTERPRISE-333](https://pokitdok.atlassian.net/browse/ENTERPRISE-333) which entailed the removal of the `payers` endpoint from the public documentation. The payers endpoint is deprecated thus we do not want any new clients using it.

ENTERPRISE-333 : Removal of `payers` from documentation

---

source/includes/_providers.md

Completion of ticket [ENTERPRISE-349](https://pokitdok.atlassian.net/browse/ENTERPRISE-349) which entailed the removal of the `year` and `role` attributes from the `provider.licenses` model.

ENTERPRISE-349 : Removal of `year` and `role` from the provider.licenses model

---

source/includes/_authentication.md

These adjustments add connection examples for the `ruby`, `csharp` and `java` client libraries to the main documentation section for https://platform.pokitdok.com/documentation/v4/#security-and-authorization

PLATFORM-4168: Update Security and Authorization Examples

---

source/includes/_scheduling.md

This PR updates our scheduling documentation to include information on Appointment.status and /schedule/appointments/uuid [PUT] w/mark_completed.

PLATFORM-4799: Updating scheduling docs to include Appointment.status

---

source/includes/_claims.md

Take coordination_of_benefits.trading_partner_id out of claim example and docs

PLATFORM-5157: Take coordination_of_benefits.trading_partner_id out of claim example and docs

---

source/includes/_claimstatus.md

Information about `status_code_value` was not included in the claims status API documentation section.   These adjustments add information about `status_code_value` including reasons why an API client may opt to reference it over the `status_code` descriptive text.  
Claims Status API response examples have also been updated to include `status_code_value`

PLATFORM-5441: include status_code_value information in claims status API documentation

---

source/includes/_claims.md

claim_level_adjustments and line_level_adjustments are not requirements on COB object, updated parameters accordingly as well as some general description clean up for these parameters.

PLATFORM-5684_Remove requirements on COB claims object

---

source/includes/_raw_x12_support.md

We recently added a Raw X12 "view" for X12 API activities on the platform.
These updates document how API clients may access the `x12_request` and `x12_response` values for their X12 API activities like eligibility and claims status (even when their original requests didn't utilize Raw X12)

X12-212: Document Raw X12 view on GET /activities/<id> requests

---

source/stylesheets/_variables.scss
source/stylesheets/screen.css.scss

this claims table is the worst scenario, other than that all other tables looks fine

X12-402: no hard break on the 1st cell; reduce sample box width

---

source/includes/_pharmacy_formulary.md

We have now added a new request field for the formulary API, `drug_class`.  This field also shows up in the API response, but as a list of all associated drug classes.
I'd love help making sure it's clear how to use the new drug class.

PHARMA-40 drug_class field for formulary API

---

source/includes/_tradingpartners.md

We have seen confusion among clients about supported search options, and how "true" they are. Since these rules were discovered and built internally, and not always given to us by the TP, we need to add a disclaimer to the docs that these rules are "subject to change".

X12-440: Update wording around supported search options

---

source/includes/_insuranceprices.md

update insurance price API docs add details about standardized amount
1. added description for `standardized` amount
2. removed `description` in response--this has been deprecated for a long time and not returned in the response.
3. also updated example document to match test mode response (CPT 99203)

SUCCESS-196 update insurance price API docs add details about standardized amount

---

source/includes/_common.md

Changes to rate limiting sections to note `per minute` rate limiting instead of hourly.
The number of requests an application can make per hour by default for rate limited resources remains the same (5K).  API client applications may request higher throttle limit values based on their specific needs and level of support.  If a 403 http status code is received, the API client application should replay that request after the rate limit period resets.

SUCCESS-316: note per minute rate limits

---

source/includes/_mpc.md

Previously, the csharp client's convenience function for `mpc` was `medicalProcedureCode`.  
This moves the example in the docs to use `mpc`, as expected per the recent update to the client. 
https://github.com/pokitdok/pokitdok-csharp/blob/master/PlatformClient.cs#L562

EV-39: update the csharp example for mpc

---

source/includes/_activities.md

This updates the API documentation for activities to mention the addition of a `tracking_description` for long running transactions like `claims`
The possible claims tracking descriptions are included so that Claims API application can reference this top level value for their claims to augment the activity workflow history information.

CLAIMS-222: summarize tracking_description values for claims activities

---

source/includes/_activities.md

These changes add fields to the activities API response for `created_date` and `last_updated_date` so API clients can more easily track these times at the top level of their activities.

CLAIMS-238: document the created_date and last_updated_date fields for activities

---

source/includes/_claims.md

These changes add a new section in the `claims` API documentation to outline some of the `MOCKPAYER` test scenarios that will result in a test claim being rejected.  
This is helpful for applications just starting out with the claims API to ensure they can properly handle different rejections that they may receive for some claims from trading partners.

CLAIMS-221: describe MOCKPAYER claims testing capabilities for exercising common rejection scenarios

---

source/includes/_scheduling.md

In TRINITY-33 (MR - https://gitlab.pokitdok.com/pokitdok/ohp/merge_requests/287) we updated the /schedule/patient [POST] endpoint to support updating a patient's demographics within an external EMR system. This MR updates the /schedule/patient [POST] description to indicate that the registration process may create or update a record within the EMR system.

TRINITY-33: updating /schedule/patient endpoint description

---

source/claim_payments.md

These changes ensure that the claim payment object reference is up-to-date in the API documentation.   The primary update contained in this set of changes is to include documentation about the `crossover_carrier` data that may be included on claim payments when the information is forwarded along to another payer after being finalized by the current payer.

SUCCESS-652: Introduce documentation for Claim Payment Crossover Carrier data

---

source/includes/_claims.md

Since the CLM01 value which maps to CLP01 of the 835 is used to insert PokitDok's encoded activity id, we are removing this from the available parameters for the claims API as the value will always be overridden.

SUCCESS-655_Remove references to patient control number

---

source/includes/_raw_x12_support.md

The description followed by the header used the wrong old header.

ENTRY-2302 Change application/vnd.pokitdok.v4+full-x12-json to application/vnd.pokitdok.v4+x12-segments-json

---

source/includes/_dropin.md

- Added missing commas in drop-in code examples
- Added missing parenthesis and semicolons on code examples
- Clarified init steps with more descriptive instructions and better code examples
- Added to drop-in bullet points to include pharma functionality
Init instructions improvements:

SUCCESS-935: Improvements to drop-in docs

---

source/includes/_appregistrations.md
source/index.md

We're adding documentation to new endpoints we've implemented to let users manage their own NPI registrations without going through the user dashboard.

SUCCESS-1883 Add NPI registration documentation.

---

source/includes/_providers.md

Updated the Providers documentation to strip out these deprecated fields:
- radius
- birth_date
- board_certifications
- board_subcertifications
- education
- facilities
- licensures
- residencies
- website_url
- locations.geo_location
Also updated the two response blocks based on actual values from the API client.

SUCCESS-3367:  Remove parameters from Providers endpoint documentation

---

Dockerfile
source/includes/_claimstatus.md
source/includes/_common.md
source/includes/_eligibility.md

Some API interactions may result in a partner returning X12 999 or TA1 data due to the way they've implemented the X12 specification (data that's generally "optional" is not optional for them, etc.)
We now link to the `errors` section from the eligibility and claim status API pages to help folks better understand these types of errors and we include an example X12 999 parsing error response.

SUCCESS-3774: document errors that may be generated by some partners and return X12 999 or TA1 data
